### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rjkip** [meenie/band.js#11]
I'm getting said error after the changes introduced in commit d11a5e54be2cc6874181f95ec4195fb92e2c051b:

Uncaught TypeError: undefined is not a function.

If I unmangle the build, it's on lines 326 and 209.

Here:

``` js
        function updateTotalPlayTime() {
            totalPlayTime += ac.currentTime - currentPlayTime;
            var seconds = Math.round(totalPlayTime);
            if (seconds != currentSeconds) {
                setTimeout(function() {
                    tickerCallback(seconds); // Here.
                }, 1);
                currentSeconds = seconds;
            }
            currentPlayTime = ac.currentTime;
        }
```

And here:

``` js
        this.stop = function(fadeOut) {
        // .....
            } else {
                totalPlayTime = 0;
                reset();
                setTimeout(function() {
                    tickerCallback(currentSeconds); // And here.
                }, 1);
```
